### ISSUE TITLE
Display potential order of future joins

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter-currency-monit#13]
Right now, we can see what are the state of certifications received. What would be perfect would be to display the order in which the identities will be able to join the WoT.

For example : 

![image](https://cloud.githubusercontent.com/assets/1170293/25388604/9657244e-29ce-11e7-9191-90f12a56795e.png)

Here we can see that Fiatoux has issued a certification to MelanieGraney and AlexisLecointe. If MelanieGraney joins the WoT, AlexisLecointe won't be able to join because Fiatoux will have a delay between the two certifications.

So the identities could be sorted with : MelanieGraney first, AlexisLecointe second.

**Comment by librelois** [comment]
Oui j'ai déjà prévu de trier les futurs membre par ordre probable d'entrée dans la WoT, mais pour le moment @devingfx m'a demander de geler le code le temps qu'on restructure correctement l'architecture, donc ce sera pas pour tout de suite !
