### ISSUE TITLE
pubkeyBalance - bad TX date ?

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter-currency-monit#44]
J'ai trouvé un truc bizarre, dans les mouvements sur ma clef g1 `38MEAZN68Pz1DTvT3tqgxx4yQP6snJCQhPqEFxbDk4aE`

[Le graphique](https://g1-monit.elois.org/pubkeyBalance?lg=fr&begin=19000&end=20100&pubkey1=38MEAZN68Pz1DTvT3tqgxx4yQP6snJCQhPqEFxbDk4aE&unit=quantitative&step=11&stepUnit=hours) indique un mouvement de -94.10 G1 le 20/05/17 :+1: 
![image](https://cloud.githubusercontent.com/assets/5269556/26390795/54bcaccc-4060-11e7-9e56-fd441a8ed5b5.png)

Or ce mouvement a été inscri en blockchain le 19/05/17 (13:32 blockchain time) - cf [block #19907](https://g1.duniter.fr/#/app/block/19907/00000400E2F2CE6FA074C99F7E264809C04D66223A4FCEFC03F11D1D756E09CA) :

![image](https://cloud.githubusercontent.com/assets/5269556/26390817/77ff7b6a-4060-11e7-85ca-ecb1200283cc.png)

Je m'en suis apercu en travaillant sur un graph similaire intégré à cesium+ : la courbe n'avait pas la même allure

**Comment by librelois** [comment]
Oui c'est parce que je calcule par tranche de 24h a partir du bloc zéro ce n'est pas intuitif je vais calculer par jour civil comme tu me l'a suggéré aux rml9 !
