### ISSUE TITLE
Display identities with a wrong blockstamp in orange too

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter-currency-monit#45]
When a certification has a wrong blockstamp, it is orange colored:

![image](https://cloud.githubusercontent.com/assets/969136/26402132/546e96d0-4089-11e7-86ac-ed4d4ea003a6.png)

But also detected 2 identities with a wrong blockstamp (`Ekiben` and `bibi`) which are displayed normally:

![image](https://cloud.githubusercontent.com/assets/969136/26402184/8039ca8c-4089-11e7-9d8e-4fac5f9be783.png)

![image](https://cloud.githubusercontent.com/assets/969136/26402198/8d6bd0e2-4089-11e7-929e-00927b772d4c.png)

So people try to certify them, but these 2 identities will never be able to join the WoT.

**Comment by librelois** [comment]
Yes, this feature is only for certifications currently. I can expand for idty :)
