### ISSUE TITLE
bug ? même identité affichée 2 fois dans le WillMembers

### ISSUE THREAD

**Issue by fiatou** [duniter/duniter-currency-monit#46]
On peut trouver Florck ici, certifié par Nartagnan et Squeeek : 
![florck](https://cloud.githubusercontent.com/assets/23424058/26657494/81e9b9ec-4664-11e7-838f-74c27bdfd5a5.png)

Puis là, certifié par Gildas... : 
![floorck](https://cloud.githubusercontent.com/assets/23424058/26657514/983881ce-4664-11e7-8e94-d4131878560a.png)

Qué pasa tio ??

**Comment by librelois** [comment]
Ce n'est pas un bug, florck avait bien publié deux identités sous le même nom et la même clé mais a deux dates différentes.
