### ISSUE TITLE
Ergonomie

### ISSUE THREAD

**Issue by galuel** [duniter/duniter-currency-monit#5]
Une liste de [boutons CSS en haut de page](http://rml.creationmonetaire.info/modules/) ferait un bon menu pour avoir par exemple : 

- https://g3.librelois.fr/willMembers
- https://g3.librelois.fr/memberswithmostcertifications
- ...
- https://g3.librelois.fr/help
- https://g3.librelois.fr/about (simple HTML page with licence link, source code link, contributors...)

La page "help" permettrait d'alléger la page actuelle en y mettant tout le texte explicatif... Remontant ainsi le tableau qui nous intéresse en haut de page.

**Comment by librelois** [comment]
J'ai ajouter un menu en haut de page ainsi qu'une page about :)

En revanche, je ne comprend pas l’intérêt d'une page help ? Ce serait pour y mettre quoi ?

**Comment by galuel** [comment]
Ah oui très bon le menu en haut ! Je vais enfin n'avoir qu'un seul bookmark au lieu de 3... Et puis je découvre tes autres créations du coup :)

> je ne comprend pas l’intérêt d'une page help ? Ce serait pour y mettre quoi ?

Ce serait pour alléger ta page qu'on ait tous les boutons sur une seule ligne y compris les cases à cocher, puis directement la liste des membres.

Dans le help tu mets tout ce texte d'intro qui du coup libèrera la place, ce serait plus propre !

PS : pour la masse monétaire ok (quoique ça me paraît bien droit comme progression, pourtant avec plus de membres ça devrait faire quelques variations...), mais alors un M/N serait bien aussi (et on verrait peut-être mieux les variations !? => Si M/N ce serait bien de penser à M/N en DU avec 3743 DU comme barre haute visible... (1/4,88% * 182,625 = 3743 DU<sub>jours</sub>), ce qui permettrait à l'utilisateur de voir combien il est loin de l'objectif "monnaie pleine" !

**Comment by librelois** [comment]
M/N ajouté, par contre pour la ligne à 3743 DU si je l'affiche on en verra plus les barres tellement elle sont petites, donc pour des raisons de visibilités ça me semble impossible pour l'instant...

**Comment by galuel** [comment]
Tu pourrais proposer une échelle logarithmique et là ça devrait coller et rester bien visible

**Comment by librelois** [comment]
Ça y ai je propose une échelle logarithmique.
Et je place automatiquement la valeur max de l'axe des ordonnées à la valeur qu'on devrait avoir en monnaie pleine, avec une explication du calcul au dessus du graphe, enjoy ?

**Comment by galuel** [comment]
Oui c'est ça. Le texte explicatif prend trop de place il devrait se retrouver dans le help pour ne pas surcharger la page et laisser l'info pure = le graphe
