### ISSUE TITLE
Wrong order of dossiers

### ISSUE THREAD

**Issue by gerard94** [duniter/duniter-currency-monit#54]
![capture d ecran de 2017-07-01 18-06-08](https://user-images.githubusercontent.com/23338182/27765461-98259978-5eb1-11e7-8e42-1e8f8d52750c.png)
Le dossier de PascaleTAINE devrait apparaître avant celui de fredverhaege puisque bou2fil (04/07/17) devrait pouvoir certifier avant Pouhiou (05/07/17) ?

**Comment by librelois** [comment]
Oui c'est exact l’algorithme actuel classe les identités en fonction de la date de disponibilité de la certification qui sera la plus tardivement disponible. Ce qui ne correspond a la date de disponibilité du dossier d'inscription que dans le cas ou l'identité à reçu sigQty certifications, si elle en a reçu d'avantage alors les deux dates ne coïncides plus. 
Je viens de corriger cette imprécision dans l’algorithme dans le commit bcefc76 :)
Une nouvelle version intégrant ce correctif sera déployée sur https://g1-monit.elois.org courant juillet, en revanche pour la version module il faudra attendre la sortie de duniter 1.4.x !
