### ISSUE TITLE
Move to duniter organization

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-currency-monit#6]
I invited you on duniter organization.

**Comment by M5oul** [comment]
Please move this project on duniter organization to let us contribute easily.
forking is a loss of time.
I don't know what didn't works.

**Comment by librelois** [comment]
"You don’t have the permission to create repositories on duniter" :
![essai-transfert-depot](https://cloud.githubusercontent.com/assets/22670546/25439619/35a70626-2a9d-11e7-873a-e172bd568f4d.png)

**Comment by c-geek** [comment]
Maybe you should transfer it to Moul first, then Moul can transfer on duniter organization.

**Comment by M5oul** [comment]
Done!
Well done!
