### ISSUE TITLE
Nouveau calculateur non répertorié ?

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter-currency-monit#65]
Hier, Framasky indiquait avoir installé son nœud Duniter.

Je vérifie ce matin, je vois bien son nœud avec sa clé personnelle sur le réseau, et je vois qu'il a calculé au moins 1 bloc avec succès !

Je m'attends donc à le trouver ici, mais il n'apparaît pas ?!

https://g1-monit.elois.org/blockCount?lg=fr&begin=0&end=42605&data=nbBlocks

**Comment by librelois** [comment]
Framasky apparaît bien avec 2 blocs calculés il est entre YohanSallami et RavanH.
