### ISSUE TITLE
Le temps blockchain est décalé

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter-currency-monit#66]
https://g1-monit.elois.org affiche ceci : 

![image](https://user-images.githubusercontent.com/969136/29485958-04f7eed4-84dc-11e7-9194-9e9ff7e547d7.png)

Or ce [block#45046](https://g1.duniter.org/blockchain/block/45046) a pour medianTime `1503134385`, ce qui donne normalement `19/08/2017 11:19`.

**Comment by librelois** [comment]
C'est l'heure GMT, le timestamp `1503134385` donne bien `19/08/2017 9:19`.

Il faut que je rajoute dans la config du module le choix de la zone horaire ou y a t'il moyen de récupérer ce paramètre via duniter ? (ce serait mieux ça éviterai a l'utilisateur de configurer sa zone pour chaque module).

**Comment by c-geek** [comment]
La timezone est directement gérable par le langage de programmation utilisé, tu peux te baser dessus à mon avis.

Donc en fait c'est bien, l'heure affichée par g1-monit est la bonne (UTC+0 ou GMT). Par contre je remarque que je me suis fait avoir par http://timestamp.fr, qui m'indique l'heure dans ma propre timezone (UTC+2).

À cela il faut ajouter le décalage d'une heure pour le `medianTime` par rapport au champ `time`, ce qui fait au total un décalage de 3 heures pour la France si l'on est en heure d'été (UTC+2) par rapport à l'heure `medianTime` UTC+0.

Pfiou, ok, tout va bien.
