### ISSUE TITLE
Linear views are not well scaled

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-currency-monit#9]
For instance, [this lineur view](https://g1-monit.elois.org/monetaryMass?begin=2&end=11602&unit=relative&massByMembers=no&type=linear) is not well scaled.
Other linear view are broken (not well scaled).

**Comment by librelois** [comment]
Ce n'est pas un bug, c'est un comportement volontaire, à la demande de Ğaluel, afin que l'on voient bien a quel point nous sommes très loin d'être en monnaie pleine !
